on:
  push:
    branches:
      - master
      - implicit-func
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'devel'}
        - { os: macOS-latest, r: 'devel'}
        - { os: ubuntu-latest, r: 'devel', rspm: "https://demo.rstudiopm.com/all/__linux__/bionic/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.rspm }}

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
          
      - name: Install system libraries
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - uses: actions/checkout@v1
          
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c('BiocManager', 'remotes', 'rcmdcheck'))
          BiocManager::install(version = 'devel', ask = FALSE, update = FALSE)
          library(remotes)
          update(dev_package_deps(dependencies = TRUE))
        shell: Rscript {0}
        
      - name: Non-windows check
        if: ${{ matrix.config.os != 'windows-latest' }}
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual'), error_on = 'warning', check_dir = 'check')"
          
      - name: Windows check
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--force-multiarch', '--install-args=`"--force-biarch`"'), error_on = 'warning', check_dir = 'check')"
          
      - name: Test coverage
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: covr::codecov()
        shell: Rscript {0}
