on:
  push:
  pull_request:
    branches:
      - master

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.bioc }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, bioc-version: 'devel'}
        - { os: macOS-latest, bioc-version: 'devel'}
        - { os: ubuntu-18.04, bioc-version: 'devel'}
        - { os: ubuntu-20.04, bioc-version: 'devel'}



    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false

      - name: Install Linux system libraries
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - name: Install Mac system libraries
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: |
          brew install libgit2
          
      - name: Install SZIP at system level
        if: ${{ matrix.config.os == 'ubuntu-18.04' }}
        run: |
          sudo apt-get install libaec-dev

      - uses: actions/checkout@v1
          
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          
      - name: Create Makevars
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: |
          mkdir $HOME/.R
          echo 'LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"' > $HOME/.R/Makevars
          echo 'CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"' >> $HOME/.R/Makevars

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c('BiocManager', 'remotes', 'rcmdcheck', 'devtools', 'testthat'), quiet = TRUE)
          BiocManager::install(version = 'devel', ask = FALSE, update = FALSE)
          library(remotes)
          update(dev_package_deps(dependencies = TRUE), quiet = TRUE)
        shell: Rscript {0}
        
      - name: Bioc - Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1
        
      - name: Test coverage
        if: ${{ matrix.config.os == 'ubuntu-20.04' }}
        run: |
          BiocManager::install('covr', update = FALSE, ask = FALSE)
          covr::codecov()
        shell: Rscript {0}
        
      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 
      
      - name: Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
        
      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.config.os }}-results
          path: ${{ steps.build-install-check.outputs.check-dir }}
          
      - name: Upload check results
        if: ${{ failure() }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-hdf5_config.log
          path: check/*.Rcheck/00_pkg_src/Rhdf5lib/src/hdf5/config.log
