on:
  push:
    branches:
      - master
      - testing-actions
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: 'devel'}
        - { os: macOS-latest, r: 'devel'}
        - { os: ubuntu-18.04, r: 'devel'}
        - { os: ubuntu-20.04, r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false
          git config --global user.email "ghau@example.com"
          git config --global user.name "GitHub Actions User"
          
      - name: Install Linux system libraries
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - name: Install Mac system libraries
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: |
          brew install libgit2

      - uses: actions/checkout@v1
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
          Ncpus: 2
          
      - name: Set R options
        run: |
          echo "options(BioC_mirror = 'https://packagemanager.rstudio.com/bioconductor')" >> ${HOME}/.Rprofile

      - name: Create Makevars
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: |
          mkdir $HOME/.R
          echo 'LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"' > $HOME/.R/Makevars
          echo 'CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"' >> $HOME/.R/Makevars

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c('BiocManager', 'remotes', 'rcmdcheck', 'devtools', 'testthat'), quiet = TRUE)
          BiocManager::install(version = 'devel', ask = FALSE, update = FALSE)
          library(remotes)
          update(dev_package_deps(dependencies = TRUE), quiet = TRUE)
        shell: Rscript {0}
        
      - name: Non-windows check
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual'), error_on = 'warning', check_dir = 'check')"
          
      - name: Test coverage
        if: ${{ matrix.config.os == 'ubuntu-20.04' }}
        run: |
          BiocManager::install('covr', update = FALSE, ask = FALSE)
          covr::codecov()
        shell: Rscript {0}
      
      - name: Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
        
      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.config.os }}-r-${{ matrix.config.r }}-results
          path: check/*.Rcheck/00install.out
          
      - name: Upload check results
        if: ${{ failure() }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-hdf5_config.log
          path: check/*.Rcheck/00_pkg_src/Rhdf5lib/src/hdf5/config.log
